spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratrip_test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use-new-id-generator-mappings: false